GET http://localhost:8000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTcxMDQ5NjQsImV4cCI6MTY1NzEwNDk4NCwiYXVkIjoiNjJjM2ZhZWVmNGRhMDBlNjk4ZTM3YzhhIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.1_Vn5QBVNp1tiP9pHC0hYwENMcy-xNleZfl75FTwMfk

###
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "email": "kadjfalkfdja@gmail.com",
    "password": "amirali1234"
}

###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "kadjfalkfdja@gmail.com",
    "password": "amirali1234"
}

###
POST http://localhost:8000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTcwMjAxMjYsImV4cCI6MTY4ODU3NzcyNiwiYXVkIjoiNjJjM2ZhZWVmNGRhMDBlNjk4ZTM3YzhhIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.0G6Khe5zSN1D_H-NWn35D231NlTGhqdt7DAEfajlHOE"
}

###
DELETE http://localhost:8000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTcxMDYwMjAsImV4cCI6MTY4ODY2MzYyMCwiYXVkIjoiNjJjNTZlNTdjN2M5ZDk5NGNkMzI0ZDg0IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.My6qCdf9nKg09u4Go7EVSH6cNJK6PJxbtJKCGSLm49I"
}